export const ADD_MOVIES = 'ADD_MOVIES';
export const ADD_GENRES = 'ADD_GENRES';
export const ADD_MOVIE_TO_FAVORITE = 'ADD_MOVIE_TO_FAVORITE';
export const REMOVE_MOVIE_TO_FAVORITE = 'REMOVE_MOVIE_TO_FAVORITE';